version: '3.7'

services:
    backend:
        build: ./backend
        container_name: docker_tp_backend
        networks:
            - my-network
        depends_on:
            - database

    database:
        build: ./database
        
        networks:
            - my-network

        container_name: db
        volumes:
            - persistence:/var/lib/postgresql/data

    httpd:
        build: ./http_server
        container_name: docker_tp_httpd
        
        ports:
            - "8888:80"
        networks:
            - my-network
        depends_on:
            - backend

networks:
    my-network: {}

volumes:
  persistence:
