---
- hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Test connection
      ping:

  roles:
    - docker
    - network
    - volume
    - launch-database
    - launch-app
    - launch-proxy
    - front
