name: Push images
on:
  #Runs when 'Run tests' succeeds and runs on main
  workflow_run:
    workflows:
      - Run tests
    types:
      - completed
    branches:
      - main

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Push the images to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push image backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-backend
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push image database
        uses: docker/build-push-action@v5
        with:
          context: ./database
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-database
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push image frontend
        uses: docker/build-push-action@v5
        with:
          context: ./http_server
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-httpd
          push: ${{ github.ref == 'refs/heads/main' }}